name: sme_app_aluno
description: SME Aplicativo do Aluno

version: 1.4.11+11

environment:
  sdk: '>=3.0.6 <4.0.0'

scripts:
  pget: flutter pub get
  brunner: flutter pub run build_runner build
  fclean: flutter clean
  icons: flutter pub run flutter_launcher_icons:main

dependencies:
  shimmer: ^3.0.0
  percent_indicator: ^4.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.3
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.4.0
  connectivity_plus: ^3.0.6 
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.5
  brasil_fields: ^1.9.1
  cpf_cnpj_validator: ^2.0.0
  json_serializable: ^6.7.1
  json_annotation: ^4.0.1
  firebase_messaging: ^14.6.5
  firebase_analytics: ^10.4.4
  intl: ^0.18.1
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: ^0.10.3
  
  device_info_plus: ^9.0.2
  url_launcher: ^6.0.10
  string_validator: ^1.0.0
  email_validator: ^2.1.17
  sentry: ^7.8.0
  awesome_dialog: ^3.0.2
  sqflite: ^2.0.2
  path: ^1.8.0 
  local_auth: ^2.1.6 
  background_fetch: ^1.1.6
  hexcolor: ^3.0.1
  get_it: ^7.1.3
  shared_preferences: ^2.0.7
  extended_masked_text: ^2.3.1
  dio: ^5.2.1+1
  grouped_list: ^5.1.2
  flutter_easyloading: ^3.0.5
  getwidget: ^3.1.1
  get_ip_address: ^0.0.5
  firebase_core: ^2.15.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2 
  flutter_lints: ^2.0.2
  build_runner: ^2.1.2 
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - config/app_config.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
