name: sme_app_aluno
description: SME Aplicativo do Aluno

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  http: ^0.12.0+4
  auto_size_text: ^2.1.0
  shared_preferences: ^0.5.6+3
  font_awesome_flutter: ^8.8.1
  package_info: ^0.4.0+16
  connectivity: ^0.4.8+2
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  brasil_fields: ^0.0.7+2
  cpf_cnpj_validator: ^1.0.5
  json_serializable: ^3.3.0
  json_annotation: ^3.0.1
  getflutter: ^1.0.11
  background_fetch: '^0.5.1'
  firebase_messaging: ^6.0.13
  intl: ^0.16.1
  flutter_html: ^0.11.1
  device_info: ^0.4.2+2
  url_launcher: ^5.4.10
  string_validator: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
